
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/macbookair/Desktop/end/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1512x982")
window.configure(bg = "#2BBAA5")


canvas = Canvas(
    window,
    bg = "#2BBAA5",
    height = 982,
    width = 1512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    270.0,
    437.0,
    anchor="nw",
    text="Your Booking is complete.\nThank you so much for visiting us",
    fill="#FFFFFF",
    font=("Inter Bold", 44 * -1)
)
window.resizable(False, False)
window.mainloop()
