
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import pymysql.cursors

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/macbookair/Desktop/inf/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1512x982")
window.configure(bg = "#2BBAA5")


def button_click():
    name1 = entry_1.get()
    stuid1 = entry_2.get()
    email1 = entry_3.get()
    np = entry_4.get()


    print(name1, stuid1, email1, np)

    conn = None
    try:
        conn = pymysql.connect(host='127.0.0.1', user='root', password='bothiccka', db='room')

    except Exception as ex:
        print('PROBLEM WITH Database Connection', ex)
    else:
        print('Database Connection SUCCESS')

    # STEP 3 - CHECK Connection is Establish or not
    if conn is not None:
        # STEP 4 Create Query
        query = "insert into info(name1, stuid1, email1, np) values (%s, %s, %s, %s) "

        try:
            # STEP 6 - CREATE cursor Object
            cursor = conn.cursor()

            # STEP 7 - EXECUTE THE Query
            noofrecoredinsert = cursor.execute(query, (name1, stuid1, email1, np))
        except Exception as e:
            print('INSERT PROBLEM ', e)
        else:
            if noofrecoredinsert > 0:
                print()
                print('RECORD INSERTED ')
                # STEP 8 - Commit Database
                conn.commit()
            else:
                print('RECORD NOT INSERTED')
        finally:
            conn.close()

canvas = Canvas(
    window,
    bg = "#2BBAA5",
    height = 982,
    width = 1512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    99.0,
    84.0,
    anchor="nw",
    text="To confirm your booking, please fill in the information below",
    fill="#FFFFFF",
    font=("Inter Bold", 44 * -1)
)

canvas.create_text(
    526.0,
    166.0,
    anchor="nw",
    text="Your Name",
    fill="#FFFFFF",
    font=("Inter Bold", 36 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    756.5,
    254.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FDFBFB",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=546.0,
    y=220.0,
    width=421.0,
    height=67.0
)

canvas.create_text(
    526.0,
    315.0,
    anchor="nw",
    text="Student ID",
    fill="#FFFFFF",
    font=("Inter Bold", 36 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    756.5,
    403.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FDFBFB",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=546.0,
    y=369.0,
    width=421.0,
    height=67.0
)

canvas.create_text(
    526.0,
    464.0,
    anchor="nw",
    text="Email",
    fill="#FFFFFF",
    font=("Inter Bold", 36 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    756.5,
    552.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FDFBFB",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=546.0,
    y=518.0,
    width=421.0,
    height=67.0
)

canvas.create_text(
    526.0,
    613.0,
    anchor="nw",
    text="Number of People",
    fill="#FFFFFF",
    font=("Inter Bold", 36 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    756.5,
    701.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FDFBFB",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=546.0,
    y=667.0,
    width=421.0,
    height=67.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button_click,
    relief="flat"
)
button_1.place(
    x=597.0,
    y=776.0,
    width=309.2152099609375,
    height=82.14543151855469
)
window.resizable(False, False)
window.mainloop()
