
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import pymysql.cursors

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/macbookair/Desktop/login/assets2/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1512x982")
window.configure(bg = "#2BBAA5")

def button_click():
    email = entry_1.get()
    password = entry_2.get()


    conn = None
    try:
        conn = pymysql.connect(host='127.0.0.1', user='root', password='bothiccka', db='room')

    except Exception as ex:
        print('PROBLEM WITH Database Connection', ex)
    else:
        print('Database Connection SUCCESS')

    # STEP 3 - CHECK Connection is Establish or not
    if conn is not None:
        # STEP 4 Create Query
        query = "insert into login(email, password) values (%s, %s) "

        try:
            # STEP 6 - CREATE cursor Object
            cursor = conn.cursor()

            # STEP 7 - EXECUTE THE Query
            noofrecoredinsert = cursor.execute(query, (email, password))
        except Exception as e:
            print('INSERT PROBLEM ', e)
        else:
            if noofrecoredinsert > 0:
                print()
                print('RECORD INSERTED ')
                # STEP 8 - Commit Database
                conn.commit()
            else:
                print('RECORD NOT INSERTED')
        finally:
            conn.close()

canvas = Canvas(
    window,
    bg = "#2BBAA5",
    height = 982,
    width = 1512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
# canvas.create_rectangle(
#     354.0,
#     262.0,
#     1155.0,
#     358.0,
#     fill="#FFFFFF",
#     outline="")

canvas.create_text(
    605.0,
    217.0,
    anchor="nw",
    text="Log In",
    fill="#FFFFFF",
    font=("Inter Bold", 96 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    754.0,
    443.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=464.0,
    y=409.0,
    width=580.0,
    height=66.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    754.0,
    610.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    show="*"
)
entry_2.place(
    x=464.0,
    y=576.0,
    width=580.0,
    height=66.0,
)

canvas.create_text(
    439.0,
    351.0,
    anchor="nw",
    text="Email",
    fill="#FFFFFF",
    font=("Inter Bold", 48 * -1)
)

canvas.create_text(
    439.0,
    507.0,
    anchor="nw",
    text="Password",
    fill="#FFFFFF",
    font=("Inter Bold", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button_click,
    relief="flat"
)
button_1.place(
    x=605.0,
    y=686.0,
    width=323.0,
    height=79.0
)

window.resizable(False, False)
window.mainloop()
