
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import pymysql.cursors

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/macbookair/Desktop/regi/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1512x982")
window.configure(bg = "#2BBAA5")


def button_click():
    name = entry_1.get()
    stuid = entry_2.get()
    email = entry_3.get()
    tel = entry_4.get()
    password = entry_5.get()

    print(name, stuid, email, tel, password)

    conn = None
    try:
        conn = pymysql.connect(host='127.0.0.1', user='root', password='bothiccka', db='room')

    except Exception as ex:
        print('PROBLEM WITH Database Connection', ex)
    else:
        print('Database Connection SUCCESS')

    # STEP 3 - CHECK Connection is Establish or not
    if conn is not None:
        # STEP 4 Create Query
        query = "insert into regi(name, stuid, email, tel, password) values (%s, %s, %s, %s, %s) "

        try:
            # STEP 6 - CREATE cursor Object
            cursor = conn.cursor()

            # STEP 7 - EXECUTE THE Query
            noofrecoredinsert = cursor.execute(query, (name, stuid, email, tel, password))
        except Exception as e:
            print('INSERT PROBLEM ', e)
        else:
            if noofrecoredinsert > 0:
                print()
                print('RECORD INSERTED ')
                # STEP 8 - Commit Database
                conn.commit()
            else:
                print('RECORD NOT INSERTED')
        finally:
            conn.close()

canvas = Canvas(
    window,
    bg = "#2BBAA5",
    height = 982,
    width = 1512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button_click,
    relief="flat"
)
button_1.place(
    x=550.0,
    y=835.0,
    width=323.0,
    height=79.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    711.0,
    768.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    show = "*"
)
entry_1.place(
    x=421.0,
    y=734.0,
    width=580.0,
    height=66.0
)

canvas.create_text(
    396.0,
    692.0,
    anchor="nw",
    text="Password",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    711.0,
    648.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=421.0,
    y=614.0,
    width=580.0,
    height=66.0
)

canvas.create_text(
    396.0,
    572.0,
    anchor="nw",
    text="Phone Number",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    711.0,
    520.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=421.0,
    y=486.0,
    width=580.0,
    height=66.0
)

canvas.create_text(
    396.0,
    444.0,
    anchor="nw",
    text="Email",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    711.0,
    392.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=421.0,
    y=358.0,
    width=580.0,
    height=66.0
)

canvas.create_text(
    396.0,
    314.0,
    anchor="nw",
    text="Student ID",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    711.0,
    276.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=421.0,
    y=242.0,
    width=580.0,
    height=66.0
)

canvas.create_text(
    396.0,
    198.0,
    anchor="nw",
    text="Full Name",
    fill="#FFFFFF",
    font=("Inter Bold", 32 * -1)
)

canvas.create_text(
    421.0,
    61.0,
    anchor="nw",
    text="Registration",
    fill="#FFFFFF",
    font=("Inter Bold", 96 * -1)
)
#window.resizable(False, False)
window.mainloop()
